[package]
name = "lkgpt"
version = "0.0.1"
edition = "2021"
rust-version.workspace = true

[dependencies]
actix-web = "4.4.0"
anyhow = "1.0.75"
dotenvy = "0.15.7"
livekit = { git = "https://github.com/livekit/rust-sdks", rev = "36d7690", features = [
  "native-tls",
] }
livekit-api = { git = "https://github.com/livekit/rust-sdks", rev = "36d7690" }
livekit-protocol = { git = "https://github.com/livekit/rust-sdks", rev = "36d7690" }
log = "0.4.20"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = ["full"] }

async-openai = "0.16.2"
chrono = "0.4.31"
futures = "0.3.29"
glam = "0.24.2"
gltf = { version = "1.3.0", features = [
  "KHR_lights_punctual",
  "KHR_materials_pbrSpecularGlossiness",
  "KHR_materials_unlit",
  "KHR_texture_transform",
  "KHR_materials_transmission",
  "KHR_materials_ior",
  "KHR_materials_variants",
  "KHR_materials_volume",
  "KHR_materials_specular",
] }
image = "0.24.7"
png = "0.17.10"
tokio-tungstenite = { version = "0.20.1", features = ["native-tls"] }
vulkano = "0.34.1"
vulkano-shaders = "0.33.0"
base64 = "0.21.5"
parking_lot = "0.12.1"
fastwebsockets = "0.5.0"
crossbeam = "0.8.2"
deepgram = "0.4.0"
async-trait = "0.1.74"
ezsockets = { version = "0.6.1", features = ["client"] }
tracing-subscriber = "0.3.18"
async-channel = "2.1.0"
bytes = "1.5.0"
url = "2.5.0"
