name: CI-TS

on:
  push:
  workflow_dispatch:

env:
  CI: true

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  ci-ts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      #  Will figure out a better way to do these later
      - name: Install Global Dependencies
        run: bun install --ignore-scripts

      #  Errors out on build when separated into multiple steps
      - name: Install
        run: bun install --ignore-scripts
      
      - name: Build
        run: bun run build
      
      - name: Lint
        run: bun run lint
